apiVersion: v1
kind: Secret
metadata:
  name: documents-secrets
  namespace: documents
type: Opaque
stringData:
  POSTGRES_DB: documents_db
  POSTGRES_USER: documents_user
  POSTGRES_PASSWORD: documents_pass