// <auto-generated />
using System;
using Documents.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Documents.Infrastructure.Migrations
{
    [DbContext(typeof(DocumentsDbContext))]
    [Migration("20260413110721_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("documents")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Documents.Core.Documents.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DescriptiveNo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descriptive_no");

                    b.Property<DateTime>("IntegratedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("integrated_at_utc");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.HasKey("Id")
                        .HasName("pk_documents");

                    b.HasIndex("DescriptiveNo")
                        .HasDatabaseName("ix_documents_descriptive_no");

                    b.HasIndex("IntegratedAtUtc")
                        .HasDatabaseName("ix_documents_integrated_at_utc");

                    b.HasIndex("Kind")
                        .HasDatabaseName("ix_documents_kind");

                    b.ToTable("documents", "documents");
                });

            modelBuilder.Entity("Documents.Core.Documents.Entities.DocumentItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArticleName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("article_name");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<decimal>("NetValue")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("net_value");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("numeric(9,4)")
                        .HasColumnName("tax_rate");

                    b.HasKey("Id")
                        .HasName("pk_document_items");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_document_items_document_id");

                    b.ToTable("document_items", "documents");
                });

            modelBuilder.Entity("Documents.Infrastructure.Persistence.Entities.IntegrationCheckpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime?>("LastProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_processed_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_integration_checkpoints");

                    b.ToTable("integration_checkpoints", "documents");
                });

            modelBuilder.Entity("Documents.Core.Documents.Entities.DocumentItem", b =>
                {
                    b.HasOne("Documents.Core.Documents.Entities.Document", "Document")
                        .WithMany("Items")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_items_documents_document_id");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Documents.Core.Documents.Entities.Document", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
